name: client-server-ci

on:
  push:
    branches:
      - main
      - client-dev
      - server-dev
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
    types: [opened, synchronize]

jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}

    env:
      NODE_VERSION: "20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          predicate-quantifier: "every"
          filters: |
            client:
              - "client/**"
              - "!client/.gitignore"
              - "!client/*.md"
              - "!client/.env.example"
            server: 
              - "server/**"
              - "!server/.gitignore"
              - "!server/*.md"
              - "!server/.env.example"

      - name: Set env for WORKDIR
        run: echo "WORKDIR=${{ steps.filter.outputs.client == 'true' && 'client' || 'server' }}" >> $GITHUB_ENV

      - name: Install node
        if: steps.filter.outputs.client == 'true' || steps.filter.outputs.server == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ env.WORKDIR }}/package-lock.json

      - name: Install dependencies
        if: steps.filter.outputs.client == 'true' || steps.filter.outputs.server == 'true'
        run: npm install
        working-directory: ${{ env.WORKDIR }}

      - name: Lint and test
        if: steps.filter.outputs.client == 'true' || steps.filter.outputs.server == 'true'
        run: |
          npm run lint
          echo "npm run test"
        working-directory: ${{ env.WORKDIR }}

      - name: Build
        if: steps.filter.outputs.client == 'true' || steps.filter.outputs.server == 'true'
        run: npm run build
        working-directory: ${{ env.WORKDIR }}

  docker:
    name: Build and push

    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && (needs.build.outputs.client == 'true' || needs.build.outputs.server == 'true') }}

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ needs.build.outputs.client == 'true' && 'client' || 'server' }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devlinks-${{ needs.build.outputs.client == 'true' && 'client' || 'server' }}:v${{ github.run_number }}
